name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        runner: [ macos, ubuntu, windows ]
        projectDir:
          - .
          - build-logic/conventions
          - build-logic/settings
          - sample
          - integration-tests
          - poc/k2-merging
    runs-on: ${{ matrix.runner }}-latest

    steps:
      - name: check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: all tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: test
          build-root-directory: ${{ matrix.projectDir }}
          write-cache-key: main-build-artifacts
          restore-cache-key: main-build-artifacts

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - unit-tests

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
